benswork/UARProject/force-app/main/default/objects/App_User__c/App_User__c.object-meta.xml
<CustomObject>
    <description>Used to determine the user who requested access to the app and the role associated to the request</description>
    <label>App User</label>
    <nameField>
        <displayFormat>U-{0}</displayFormat>
        <label>App User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

benswork/UARProject/force-app/main/default/objects/App_User__c/fields/App__c.field-meta.xml
<CustomField>
    <fullName>App__c</fullName>
    <label>App</label>
    <referenceTo>Apps__c</referenceTo>
    <relationshipLabel>App Users</relationshipLabel>
    <relationshipName>App_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/App_User__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Role</label>
    <referenceTo>App_Role__c</referenceTo>
    <relationshipLabel>App Users</relationshipLabel>
    <relationshipName>App_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/App_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person Account of the User</description>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You must select a person account!</errorMessage>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>App Users</relationshipLabel>
    <relationshipName>App_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/classes/scheduleAssignUserApp.cls
public class scheduleAssignUserApp  implements schedulable {
	
    public static id JobId {get;set;}
    
    public void execute(System.SchedulableContext SC){
		
		JobId = SC.getTriggerId();
		CronTrigger ct = [SELECT Id, CronJobDetail.Name FROM CronTrigger WHERE Id = :SC.getTriggerId()];
		
		string appUserId = ct.CronJobDetail.Name.removeEnd('--scheduleAssignUserApp');
		
  		if ((appUserId.length() == 18 || appUserId.length() == 15) && appUserId.substring(0,3) == 'a0F' ) {
			App_User__c au = [SELECT Name, Role__c, User__r.HashId__pc, App__c FROM App_User__c WHERE Id = :appUserId];
			assignUserApp.assignUserApp(au.App__c , au.User__r.HashId__pc);
  		}

		system.abortJob(JobId);
			 
	}    
    
}