benswork/UARProject/force-app/main/default/objects/Access_Request__c/Access_Request__c.object-meta.xml
<CustomObject>
    <label>Access Request</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Access Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

benswork/UARProject/force-app/main/default/objects/Access_Request__c/fields/App__c.field-meta.xml
<CustomField>
    <fullName>App__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>App</label>
    <referenceTo>Apps__c</referenceTo>
    <relationshipLabel>Access Requests</relationshipLabel>
    <relationshipName>Access_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/Access_Request__c/fields/App_User__c.field-meta.xml
<CustomField>
    <fullName>App_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>App User</label>
    <referenceTo>App_User__c</referenceTo>
    <relationshipLabel>Access Requests</relationshipLabel>
    <relationshipName>Access_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/Access_Request__c/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Persona</label>
    <referenceTo>App_Role__c</referenceTo>
    <relationshipLabel>Access Requests</relationshipLabel>
    <relationshipName>Access_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/Access_Request__c/fields/Request_Owner__c.field-meta.xml
<CustomField>
    <fullName>Request_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requester</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Access Requests (Request Owner)</relationshipLabel>
    <relationshipName>Access_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/Access_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved by Supervisor</fullName>
            </value>
            <value>
                <fullName>Approved by Business Owner</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

benswork/UARProject/force-app/main/default/objects/App_Role__c/App_Role__c.object-meta.xml
<CustomObject>
    <label>App Role</label>
    <nameField>
        <label>AppRole Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>App Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

benswork/UARProject/force-app/main/default/objects/App_Role__c/fields/App__c.field-meta.xml
<CustomField>
    <fullName>App__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>App</label>
    <referenceTo>Apps__c</referenceTo>
    <relationshipLabel>App Roles</relationshipLabel>
    <relationshipName>App_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/App_User__c/App_User__c.object-meta.xml
<CustomObject>
    <description>Used to determine the user who requested access to the app and the role associated to the request</description>
    <label>App User</label>
    <nameField>
        <displayFormat>U-{0}</displayFormat>
        <label>App User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

benswork/UARProject/force-app/main/default/objects/App_User__c/fields/App__c.field-meta.xml
<CustomField>
    <fullName>App__c</fullName>
    <label>App</label>
    <referenceTo>Apps__c</referenceTo>
    <relationshipLabel>App Users</relationshipLabel>
    <relationshipName>App_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/App_User__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Role</label>
    <referenceTo>App_Role__c</referenceTo>
    <relationshipLabel>App Users</relationshipLabel>
    <relationshipName>App_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/App_User__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

benswork/UARProject/force-app/main/default/objects/App_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person Account of the User</description>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You must select a person account!</errorMessage>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>App Users</relationshipLabel>
    <relationshipName>App_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/App_User_Group__c/App_User_Group__c.object-meta.xml
<CustomObject>
    <label>App User Group</label>
    <nameField>
        <displayFormat>AUG-{0000}</displayFormat>
        <label>App User Group ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App User Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

benswork/UARProject/force-app/main/default/objects/App_User_Group__c/fields/Access_Request__c.field-meta.xml
<CustomField>
    <fullName>Access_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Access Request</label>
    <referenceTo>Access_Request__c</referenceTo>
    <relationshipLabel>App User Groups</relationshipLabel>
    <relationshipName>App_User_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/App_User_Group__c/fields/App_User__c.field-meta.xml
<CustomField>
    <fullName>App_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>App User</label>
    <referenceTo>App_User__c</referenceTo>
    <relationshipLabel>App User Groups</relationshipLabel>
    <relationshipName>App_User_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/App_User_Group__c/fields/Approval_Required__c.field-meta.xml
<CustomField>
    <fullName>Approval_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Approval Required?</label>
    <type>Checkbox</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/App_User_Group__c/fields/Related_Groups__c.field-meta.xml
<CustomField>
    <fullName>Related_Groups__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Groups</label>
    <referenceTo>Related_Groups__c</referenceTo>
    <relationshipLabel>App User Groups</relationshipLabel>
    <relationshipName>App_User_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/App_User_Role__c/App_User_Role__c.object-meta.xml
<CustomObject>
    <label>App User Role</label>
    <nameField>
        <displayFormat>AUR-{0000}</displayFormat>
        <label>App User Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App User Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

benswork/UARProject/force-app/main/default/objects/App_User_Role__c/fields/Access_Request__c.field-meta.xml
<CustomField>
    <fullName>Access_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Access Request</label>
    <referenceTo>Access_Request__c</referenceTo>
    <relationshipLabel>App User Roles</relationshipLabel>
    <relationshipName>App_User_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/App_User_Role__c/fields/App_Role__c.field-meta.xml
<CustomField>
    <fullName>App_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>App Role</label>
    <referenceTo>App_Role__c</referenceTo>
    <relationshipLabel>App User Roles</relationshipLabel>
    <relationshipName>App_User_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/App_User_Role__c/fields/App_User__c.field-meta.xml
<CustomField>
    <fullName>App_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>App User</label>
    <referenceTo>App_User__c</referenceTo>
    <relationshipLabel>App User Roles</relationshipLabel>
    <relationshipName>App_User_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/Apps__c/Apps__c.object-meta.xml
<CustomObject>
    <description>Business Applications supporting agency operations</description>
    <label>App</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

benswork/UARProject/force-app/main/default/objects/Apps__c/fields/App__c.field-meta.xml
<CustomField>
    <fullName>App__c</fullName>
    <description>Categories of Apps</description>
    <label>App Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrative</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Productivity</fullName>
            </value>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Collaboration</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

benswork/UARProject/force-app/main/default/objects/Apps__c/fields/Group_Helptext__c.field-meta.xml
<CustomField>
    <fullName>Group_Helptext__c</fullName>
    <label>Group Helptext</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/Apps__c/fields/Role_Helptext__c.field-meta.xml
<CustomField>
    <fullName>Role_Helptext__c</fullName>
    <label>Role Helptext</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/Related_Groups__c/Related_Groups__c.object-meta.xml
<CustomObject>
    <label>Related Groups</label>
    <nameField>
        <label>Related Groups Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Related Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

benswork/UARProject/force-app/main/default/objects/Related_Groups__c/fields/App__c.field-meta.xml
<CustomField>
    <fullName>App__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>App</label>
    <referenceTo>Apps__c</referenceTo>
    <relationshipLabel>Related Groups</relationshipLabel>
    <relationshipName>Related_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/classes/LP_CreateUARCtrl.cls
/**
*------------------------------------------------------------------------------------------------------
* @Name             LP_CreateUARCtrl
* @Author           Nikhil Kulkarni (Deloitte Consulting) <nikkulkarni@deloitte.com>
* @ModifiedBy       Nikhil Kulkarni (Deloitte Consulting) <nikkulkarni@deloitte.com>
* @Version          v1.0
* @CreatedDate      09/17/2018
* @UsedBy           LP_CreateUARCmp
* @TestClass        LP_CreateUARCtrl_Test
*------------------------------------------------------------------------------------------------------
* @Description
* Server side Apex methods for the LP_CreateUARCmp
*------------------------------------------------------------------------------------------------------
* @Changes
*
*------------------------------------------------------------------------------------------------------
**/
public with sharing class LP_CreateUARCtrl {

    public class groupWrapper{
        @AuraEnabled public Id id {get;set;}
        @AuraEnabled public String label {get;set;}
        @AuraEnabled public String value {get;set;}
        @AuraEnabled public Boolean selected {get;set;}
        @AuraEnabled public String description {get;set;}

        public groupWrapper(Id valueId, String valueLabel, String valueValue, Boolean valueSelected, String valueDescription){
            this.id             = valueId;
            this.label          = valueLabel;
            this.value          = valueValue;
            this.selected       = valueSelected;
            this.description    = valueDescription;
        }
    }

    public class roleWrapper{
        @AuraEnabled public Id id {get;set;}
        @AuraEnabled public String label {get;set;}
        @AuraEnabled public String value {get;set;}
        @AuraEnabled public Boolean selected {get;set;}
        @AuraEnabled public String description {get;set;}

        public roleWrapper(Id valueId, String valueLabel, String valueValue, Boolean valueSelected){
            this.id             = valueId;
            this.label          = valueLabel;
            this.value          = valueValue;
            this.selected       = valueSelected;
        }
    }

    public class initWrapper{
        @AuraEnabled public List<groupWrapper> appGroups {get;set;}
        @AuraEnabled public List<roleWrapper> appRoles {get;set;}
        @AuraEnabled public Id currentUserRelatedPersonAccountId {get;set;}
        @AuraEnabled public String appText{get;set;}
        @AuraEnabled public String appGroupText{get;set;}
    }

    @AuraEnabled
    public static initWrapper initialize(Id appId){
        initWrapper returnResult = new initWrapper();

        returnResult.appGroupText                       = getGroupText(appId);
        returnResult.appText                            = getAppText(appId);
        returnResult.appGroups                          = getRelatedGroups(appId);
        returnResult.appRoles                           = getAppRoles(appId);
        returnResult.currentUserRelatedPersonAccountId  = CBP_Utils.getCurrentUserRelatedPersonAccountId();

        return returnResult;
    }
    @AuraEnabled
    public static String getGroupText(Id appId){
        String helptext = [SELECT Id, Name, Group_Helptext__c FROM Apps__c WHERE Id =: appId].Group_Helptext__c;
        return helptext;
    }

    @AuraEnabled
    public static String getAppText(Id appId){
        String helptext = [SELECT Id, Name, Role_Helptext__c FROM Apps__c WHERE Id =: appId].Role_Helptext__c;
        return helptext;
    }

    @AuraEnabled
    public static List<groupWrapper> getRelatedGroups(Id appId){

        List<groupWrapper> groups = new List<groupWrapper>();

        for(Related_Groups__c relatedGroup : [SELECT Id, Name, Description__c FROM Related_Groups__c WHERE App__c =: appId ORDER BY Name ASC]){
            groups.add(new groupWrapper(relatedGroup.Id, relatedGroup.Name, relatedGroup.Id, false, relatedGroup.Description__c));
        }

        return groups;
    }

    @AuraEnabled
    public static List<roleWrapper> getAppRoles(Id appId){

        List<roleWrapper> roles = new List<roleWrapper>();

        for(App_Role__c relatedApp : [SELECT Id, Name FROM App_Role__c WHERE App__c =: appId ORDER BY Name ASC]){
            roles.add(new roleWrapper(relatedApp.Id, relatedApp.Name, relatedApp.Id, false));
        }

        return roles;
    }

    @AuraEnabled
    public static void createAppRequest(Access_Request__c newAppRequest, List<String> appRoleIds, List<String> appGroupIds){

        List<App_User_Role__c> appUserRoles = new List<App_User_Role__c>();
        List<App_User_Group__c> appUserGroups = new List<App_User_Group__c>();
        List<App_Role__c> appRoles = [SELECT Id, Approval_Required__c FROM App_Role__c WHERE Id IN: appRoleIds];
        List<Related_Groups__c> appGroups = [SELECT Id, Approval_Required__c FROM Related_Groups__c WHERE Id IN: appGroupIds];

        App_User__c AppUser = new App_User__c();

        list<App_User__c> AppUsers = [SELECT Id from App_User__c WHERE App__c = :newAppRequest.App__c AND User__c = :newAppRequest.Request_Owner__c LIMIT 1];
        if (AppUsers.size() > 0) {
            AppUser = AppUsers[0];
            AppUser.Role__c = appRoleIds[0];
            AppUser.Status__c = 'Pending';
            update AppUser;
        } else {
            AppUser = new App_User__c(
                App__c = newAppRequest.App__c,
                User__c = newAppRequest.Request_Owner__c,
                Role__c = appRoleIds[0],
                Status__c = 'Pending'
            );
	        insert AppUser;
        }
        
        newAppRequest.App_User__c = AppUser.Id;
        newAppRequest.Persona__c = appRoleIds[0];

        insert newAppRequest;

        for(App_Role__c appRole : appRoles){
            appUserRoles.add(
                    new App_User_Role__c(
                            Access_Request__c = newAppRequest.Id,
                            App_User__c = AppUser.Id,
                            Approval_Required__c = appRole.Approval_Required__c,
                            App_Role__c = appRole.Id
                    )
            );
        }

        for(Related_Groups__c appGroup : appGroups){
            appUserGroups.add(
                    new App_User_Group__c(
                            Access_Request__c = newAppRequest.Id,
                            Approval_Required__c = appGroup.Approval_Required__c,
                            Related_Groups__c = appGroup.Id,
							App_User__c = AppUser.Id
                    )
            );
        }

        insert appUserRoles;

        insert appUserGroups;

    }
    @AuraEnabled
    public static void updateRecords(String recordId, List<String> docIds){
        List<ContentDocumentLink> cdLinks = new List<ContentDocumentLink> ();
         for (String cdId : docIds){
            ContentDocumentLink link = new ContentDocumentLink();
            link.LinkedEntityId = recordId;
            link.ContentDocumentId = cdId;
            link.ShareType = 'V';
            cdLinks.add(link);
        }   
        insert cdLinks;
    }

}