benswork/UARProject/force-app/main/default/objects/Access_Request__c/Access_Request__c.object-meta.xml
<CustomObject>
    <label>Access Request</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Access Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

benswork/UARProject/force-app/main/default/objects/Access_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supervisor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Access Requests</relationshipLabel>
    <relationshipName>Access_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/Access_Request__c/fields/App__c.field-meta.xml
<CustomField>
    <fullName>App__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>App</label>
    <referenceTo>Apps__c</referenceTo>
    <relationshipLabel>Access Requests</relationshipLabel>
    <relationshipName>Access_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/Access_Request__c/fields/App_User__c.field-meta.xml
<CustomField>
    <fullName>App_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>App User</label>
    <referenceTo>App_User__c</referenceTo>
    <relationshipLabel>Access Requests</relationshipLabel>
    <relationshipName>Access_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/App_Role__c/App_Role__c.object-meta.xml
<CustomObject>
    <label>App Role</label>
    <nameField>
        <label>AppRole Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>App Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

benswork/UARProject/force-app/main/default/objects/App_Role__c/fields/App__c.field-meta.xml
<CustomField>
    <fullName>App__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>App</label>
    <referenceTo>Apps__c</referenceTo>
    <relationshipLabel>App Roles</relationshipLabel>
    <relationshipName>App_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/App_Role__c/fields/License_Type__c.field-meta.xml
<CustomField>
    <fullName>License_Type__c</fullName>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Salesforce Platform</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

benswork/UARProject/force-app/main/default/objects/App_User__c/App_User__c.object-meta.xml
<CustomObject>
    <description>Used to determine the user who requested access to the app and the role associated to the request</description>
    <label>App User</label>
    <nameField>
        <displayFormat>U-{0}</displayFormat>
        <label>App User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

benswork/UARProject/force-app/main/default/objects/App_User__c/fields/App__c.field-meta.xml
<CustomField>
    <fullName>App__c</fullName>
    <label>App</label>
    <referenceTo>Apps__c</referenceTo>
    <relationshipLabel>App Users</relationshipLabel>
    <relationshipName>App_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/App_User__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Role</label>
    <referenceTo>App_Role__c</referenceTo>
    <relationshipLabel>App Users</relationshipLabel>
    <relationshipName>App_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/App_User_Group__c/App_User_Group__c.object-meta.xml
<CustomObject>
    <label>App User Group</label>
    <nameField>
        <displayFormat>AUG-{0000}</displayFormat>
        <label>App User Group ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App User Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

benswork/UARProject/force-app/main/default/objects/App_User_Group__c/fields/App_User__c.field-meta.xml
<CustomField>
    <fullName>App_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>App User</label>
    <referenceTo>App_User__c</referenceTo>
    <relationshipLabel>App User Groups</relationshipLabel>
    <relationshipName>App_User_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/App_User_Group__c/fields/Related_Groups__c.field-meta.xml
<CustomField>
    <fullName>Related_Groups__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Groups</label>
    <referenceTo>Related_Groups__c</referenceTo>
    <relationshipLabel>App User Groups</relationshipLabel>
    <relationshipName>App_User_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/App_User_Role__c/App_User_Role__c.object-meta.xml
<CustomObject>
    <label>App User Role</label>
    <nameField>
        <displayFormat>AUR-{0000}</displayFormat>
        <label>App User Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App User Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

benswork/UARProject/force-app/main/default/objects/App_User_Role__c/fields/App_Role__c.field-meta.xml
<CustomField>
    <fullName>App_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>App Role</label>
    <referenceTo>App_Role__c</referenceTo>
    <relationshipLabel>App User Roles</relationshipLabel>
    <relationshipName>App_User_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/App_User_Role__c/fields/App_User__c.field-meta.xml
<CustomField>
    <fullName>App_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>App User</label>
    <referenceTo>App_User__c</referenceTo>
    <relationshipLabel>App User Roles</relationshipLabel>
    <relationshipName>App_User_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/Apps__c/Apps__c.object-meta.xml
<CustomObject>
    <description>Business Applications supporting agency operations</description>
    <label>App</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

benswork/UARProject/force-app/main/default/objects/Apps__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Apps</relationshipLabel>
    <relationshipName>Business_Apps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/Apps__c/fields/App__c.field-meta.xml
<CustomField>
    <fullName>App__c</fullName>
    <description>Categories of Apps</description>
    <label>App Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrative</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Productivity</fullName>
            </value>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Collaboration</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

benswork/UARProject/force-app/main/default/objects/Apps__c/fields/Business_Owner__c.field-meta.xml
<CustomField>
    <fullName>Business_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Apps (Business Owner)</relationshipLabel>
    <relationshipName>Apps</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/Apps__c/fields/Org__c.field-meta.xml
<CustomField>
    <fullName>Org__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the Org where the application is available</description>
    <label>Org</label>
    <referenceTo>Org__c</referenceTo>
    <relationshipName>Apps</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/Apps__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>Stage of the Application</description>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ideation</fullName>
            </value>
            <value>
                <fullName>Discovery/Prioritization</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Deployment</fullName>
            </value>
            <value>
                <fullName>Pilot</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

benswork/UARProject/force-app/main/default/objects/Org__c/Org__c.object-meta.xml
<CustomObject>
    <description>Cloud instance i.e. Salesforce Org</description>
    <label>Org</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

benswork/UARProject/force-app/main/default/objects/Org__c/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <label>Named Credential</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/Org__c/fields/Org_Type__c.field-meta.xml
<CustomField>
    <fullName>Org_Type__c</fullName>
    <label>Org Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Shared</fullName>
            </value>
            <value>
                <fullName>Single</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

benswork/UARProject/force-app/main/default/objects/Permission_Set__c/Permission_Set__c.object-meta.xml
<CustomObject>
    <label>Permission Set</label>
    <nameField>
        <label>Permission Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permission Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

benswork/UARProject/force-app/main/default/objects/Permission_Set__c/fields/App__c.field-meta.xml
<CustomField>
    <fullName>App__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>App that uses this Permission Set</description>
    <label>App</label>
    <referenceTo>Apps__c</referenceTo>
    <relationshipLabel>Permission Sets</relationshipLabel>
    <relationshipName>Permission_Sets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/Related_Groups__c/Related_Groups__c.object-meta.xml
<CustomObject>
    <label>Related Groups</label>
    <nameField>
        <label>Related Groups Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Related Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

benswork/UARProject/force-app/main/default/objects/Related_Groups__c/fields/App__c.field-meta.xml
<CustomField>
    <fullName>App__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>App</label>
    <referenceTo>Apps__c</referenceTo>
    <relationshipLabel>Related Groups</relationshipLabel>
    <relationshipName>Related_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/Role_Permission__c/Role_Permission__c.object-meta.xml
<CustomObject>
    <label>Role Permission</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Role Permission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Permissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

benswork/UARProject/force-app/main/default/objects/Role_Permission__c/fields/App_Role__c.field-meta.xml
<CustomField>
    <fullName>App_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>App Role</label>
    <referenceTo>App_Role__c</referenceTo>
    <relationshipLabel>Role Permissions</relationshipLabel>
    <relationshipName>Role_Permissions</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/Role_Permission__c/fields/Permission_Set__c.field-meta.xml
<CustomField>
    <fullName>Permission_Set__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Permission Set</label>
    <referenceTo>Permission_Set__c</referenceTo>
    <relationshipLabel>Role Permissions</relationshipLabel>
    <relationshipName>Role_Permissions</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/classes/assignUserAppExistingUserTest.cls
@isTest
public class assignUserAppExistingUserTest{ 
   
    @TestSetUp
    Static void setup()
    {
        Profile MyProfile = [SELECT Id from Profile WHERE Name = 'CBP Standard User'];
    	User usr1 = new User();
		usr1.FirstName = 'Tom';
		usr1.lastname = 'Brady';
		usr1.federationidentifier = '1234abcd';
	    usr1.ProfileId = MyProfile.Id;
	    usr1.UserName='Tom.Brady@associates.cbp.dhs.gov.abc.def.ghi.123.456.sandbox'; // ought to be random enough
	    usr1.EMail= 'Tom.Brady@associates.cbp.dhv.gov.invalid';
	    usr1.Alias='tbrady';
	    usr1.TimeZoneSidKey= 'America/New_York';
	    usr1.LocaleSidKey= 'En_US';
	    usr1.EmailEncodingKey= 'UTF-8';
	    usr1.LanguageLocaleKey= 'En_US';
	    usr1.IsActive=true;
	    

		User usr2 = new User();
		usr2.FirstName = 'Bill';
		usr2.lastname = 'Belichik';
		usr2.federationidentifier = '5678efgh';
	    usr2.ProfileId = MyProfile.Id;
	    usr2.UserName='Bill.Belichik@associates.cbp.dhs.gov.abc.def.ghi.123.456.sandbox'; // ought to be random enough
	    usr2.EMail= 'Bill.Belichik@associates.cbp.dhv.gov.invalid';
	    usr2.Alias='bbelich';
	    usr2.TimeZoneSidKey= 'America/New_York';
	    usr2.LocaleSidKey= 'En_US';
	    usr2.EmailEncodingKey= 'UTF-8';
	    usr2.LanguageLocaleKey= 'En_US';
	    usr2.IsActive=true;
	    List<User> usr = new List<User>();
        usr.add(usr1);
        usr.add(usr2);
        insert usr;

		List<Account> acct = new List<Account>();
        Account acct1 = new Account(firstname = 'Tom', lastname='Brady', HashId__pc='1234abcd', recordTypeId='012t000000008i6AAA', related_User__pc = usr1.id);
        Account acct2 = new Account(firstname = 'Bill', lastname='Belichek', HashId__pc='5678efgh', recordTypeId='012t000000008i6AAA', related_User__pc = usr2.id);
        acct.add(acct1);
        acct.add(acct2);
        insert acct;

		NamedCredential nc = [select id, DeveloperName from namedcredential limit 1];
		
        Org__c org = new Org__c();
        org.Name = 'My Test CBP Org';
        org.Named_Credential__c = nc.DeveloperName;
        org.Org_Type__c = 'Shared';
        insert org;
        
        Apps__c app = new Apps__c();
        app.name = 'My Test CBP App';
        app.Org__c = org.id;
        app.Account__c = acct1.id;
        app.app__c = 'Productivity';
        app.Business_Owner__c = acct1.id;
        app.Stage__c = 'Live';
        insert app;
        List<Permission_Set__c> ps = new List<Permission_Set__c>();
        Permission_Set__c ps1 = new Permission_Set__c(Name='PermSet1', API_Name__c = 'PermSet1', App__c = app.Id);
        Permission_Set__c ps2 = new Permission_Set__c(Name='PermSet2', API_Name__c = 'PermSet2', App__c = app.Id);
        ps.add(ps1);
        ps.add(ps2);
        insert ps;
        App_Role__c ar = new App_Role__c(Name='AppUser', App__c = app.id, License_Type__c = 'Salesforce', Description__c='Description');
        insert ar;
        
        Related_Groups__c rg1 = new Related_Groups__c(Name='MyGroup1', API_Name__c = 'MyGroup1', App__c = app.Id);
        insert rg1;
        
        List<Role_Permission__c> rp = new List<Role_Permission__c>();
        Role_Permission__c rp1 = new Role_Permission__c(App_Role__c = ar.id, Permission_Set__c = ps1.id);
        Role_Permission__c rp2 = new Role_Permission__c(App_Role__c = ar.id, Permission_Set__c = ps2.id);
        rp.add(rp1);
        rp.add(rp2);
        insert rp;
        List<App_User__c> au = new List<App_User__c>();
        App_User__c au1 = new App_User__c(User__c = acct1.id, App__c = app.id, role__c = ar.id);
        App_User__c au2 = new App_User__c(User__c = acct2.id, App__c = app.id, role__c = ar.id);
        au.add(au1);
        au.add(au2);
        insert au;
        
        List<Access_Request__c> acr = new List<Access_Request__c>();
        Access_Request__c acr1 = new Access_Request__c(App_User__c = au1.id, Status__c = 'Approved', App__c=app.Id, Persona__c = ar.id);
        Access_Request__c acr2 = new Access_Request__c(App_User__c = au2.id, Status__c = 'Approved', App__c=app.Id, Persona__c = ar.id);
        acr.add(acr1);
        acr.add(acr2);
        insert acr;
        
        List<App_User_Group__c> aug = new List<App_User_Group__c>();
        App_User_Group__c aug1 = new App_User_Group__c(Access_Request__c = acr1.id, App_User__c = au1.id, Approval_Required__c = true, Related_Groups__c = rg1.id);
        App_User_Group__c aug2 = new App_User_Group__c(Access_Request__c = acr2.id, App_User__c = au2.id, Approval_Required__c = true, Related_Groups__c = rg1.id);
        aug.add(aug1);
        aug.add(aug2);
        insert aug;
        
         List<App_User_Role__c> aur = new List<App_User_Role__c>();
         App_User_Role__c aur1 = new App_User_Role__c (
                                                    Access_Request__c = acr1.id, 
                                                    Access_Request_Approved__c= 'Approved',
                                                    App_Role__c= ar.id,
                                                    Approval_Required__c=True,
                                                    App_User__c = au1.id
                                                    ); 

        App_User_Role__c aur2 = new App_User_Role__c (
                                                    Access_Request__c = acr1.id, 
                                                    Access_Request_Approved__c= 'Approved',
                                                    App_Role__c= ar.id,
                                                    Approval_Required__c=True,
                                                    App_User__c = au2.id
                                                    ); 
        aur.add(aur1);
        aur.add(aur2);
        insert aur ;
    }
    
    static testMethod void assignUserApp_Test() {
        Apps__c app1 = [select id from Apps__c limit 1];
        App_User__c AU1 =[select id from App_User__c limit 1];
      
        Test.setMock(HttpCalloutMock.class, new mockassignUserAppGenerator(true));
		assignuserApp.CreateUserPersonAccount((string)au1.id);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new mockassignUserAppGenerator(true));
		assignuserApp.assignUserApp(app1.Id, '1234abcd');
        
        Test.stopTest();
    }
	
    
    static testMethod void assignUserAppBadRequest_Test() {
        Apps__c app1 = [select id from Apps__c limit 1];
        Account acc1 = [select id  from Account where FirstName = 'Tom' limit 1];
        App_User__c AU1 =[select id from App_User__c where User__c =: acc1.id];
        
        Test.setMock(HttpCalloutMock.class, new mockassignUserAppGenerator(False));
		assignuserApp.CreateUserPersonAccount((string)au1.id);
        Test.startTest();

        try{
         	Test.setMock(HttpCalloutMock.class, new mockassignUserAppGenerator(False));
            assignuserApp.assignUserApp(app1.Id, '5678efgh');
        	}
        catch(Exception e){
            system.debug('@@@exception' + e.getMessage());
          	System.assert(e.getMessage().contains('Remote system did not respond properly to Profile Query'));
        }
        Test.stopTest();
        
            }
}