benswork/UARProject/force-app/main/default/objects/Access_Request__c/Access_Request__c.object-meta.xml
<CustomObject>
    <label>Access Request</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Access Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

benswork/UARProject/force-app/main/default/objects/Access_Request__c/fields/App__c.field-meta.xml
<CustomField>
    <fullName>App__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>App</label>
    <referenceTo>Apps__c</referenceTo>
    <relationshipLabel>Access Requests</relationshipLabel>
    <relationshipName>Access_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/Access_Request__c/fields/App_User__c.field-meta.xml
<CustomField>
    <fullName>App_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>App User</label>
    <referenceTo>App_User__c</referenceTo>
    <relationshipLabel>Access Requests</relationshipLabel>
    <relationshipName>Access_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/Access_Request__c/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Persona</label>
    <referenceTo>App_Role__c</referenceTo>
    <relationshipLabel>Access Requests</relationshipLabel>
    <relationshipName>Access_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/Access_Request__c/fields/Request_Owner__c.field-meta.xml
<CustomField>
    <fullName>Request_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requester</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Access Requests (Request Owner)</relationshipLabel>
    <relationshipName>Access_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/Access_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved by Supervisor</fullName>
            </value>
            <value>
                <fullName>Approved by Business Owner</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

benswork/UARProject/force-app/main/default/objects/App_User__c/App_User__c.object-meta.xml
<CustomObject>
    <description>Used to determine the user who requested access to the app and the role associated to the request</description>
    <label>App User</label>
    <nameField>
        <displayFormat>U-{0}</displayFormat>
        <label>App User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

benswork/UARProject/force-app/main/default/objects/App_User__c/fields/App__c.field-meta.xml
<CustomField>
    <fullName>App__c</fullName>
    <label>App</label>
    <referenceTo>Apps__c</referenceTo>
    <relationshipLabel>App Users</relationshipLabel>
    <relationshipName>App_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/App_User__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Role</label>
    <referenceTo>App_Role__c</referenceTo>
    <relationshipLabel>App Users</relationshipLabel>
    <relationshipName>App_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/objects/App_User__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

benswork/UARProject/force-app/main/default/objects/App_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person Account of the User</description>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You must select a person account!</errorMessage>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>App Users</relationshipLabel>
    <relationshipName>App_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

benswork/UARProject/force-app/main/default/classes/accessRequestTriggerHandler.cls
public class accessRequestTriggerHandler {
    
    public static void IsBeforeInsert(list<Access_Request__c> nList) { 

    	set<Id> UserIds = new set<Id>();
    	set<Id> AppIds = new set<Id>();
    	for(Access_Request__c ar1 : nList) {
    		UserIds.add(ar1.Request_Owner__c);
    		AppIds.add(ar1.App__c);	
    	}
    	list<App_User__c> curAppUsers = [SELECT Id, App__c, User__c FROM App_User__c WHERE App__c IN :AppIds AND User__C IN :UserIds];
    	for(Access_Request__c ar2 : nList) {
    		for (App_User__c au : curAppUsers) {
    			if (au.App__c == ar2.App__c && au.User__c == ar2.Request_Owner__c) {
    				ar2.App_User__c = au.Id;
    			}
    		}
    	}
    }

    public static void IsBeforeUpdate(list<Access_Request__c> nList, map<Id, Access_Request__c> nMap, list<Access_Request__c> oList, map<Id, Access_Request__c> oMap) { 

        map<Id, Id> AppRoles = new map<Id, Id>(); 
        list<App_User__c> newAUs = new list<App_User__c>();
        for (Access_Request__c ar1 : nlist) {
            if (ar1.Status__c == 'Approved' && oMap.get(ar1.Id).Status__c != 'Approved') {
                if(ar1.App_User__c != null) {
                	AppRoles.put(ar1.App_User__c, ar1.Persona__c);
                }
            }
        }
        if (newAUs.size() > 0) {
        	insert newAUs;
	    	for(Access_Request__c ar2 : nList) {
	    		for (App_User__c au : newAUs) {
	    			if (au.App__c == ar2.App__c && au.User__c == ar2.Request_Owner__c) {
	    				ar2.App_User__c = au.Id;
	    			}
	    		}
	    	}
        }
        if(AppRoles.Keyset().size() > 0) {
        	list<App_User__c> AUs = [SELECT Id, Role__c FROM App_User__c where Id in :AppRoles.Keyset()];
        	for (App_User__c a : AUs) {
        		a.Role__c = AppRoles.get(a.Id);
                a.Status__c = 'Pending';
        	}
        	update AUs;
        }
    }

    public static void IsAfterInsert(list<Access_Request__c> nList) { }

    public static void IsAfterUpdate(list<Access_Request__c> nList, map<Id, Access_Request__c> nMap, list<Access_Request__c> oList, map<Id, Access_Request__c> oMap) {
        
        set<Id> AccountIds = new set<Id>();

        for (Access_Request__c a : nList) {
            AccountIds.add(a.Request_Owner__c);
        }
        map<Id, Account> HashIds = new map<Id, Account>([SELECT Id, HashId__pc FROM Account WHERE Id IN :AccountIds]);
        
        for (Access_Request__c ar : nlist) {
            if (ar.Status__c == 'Approved' && oMap.get(ar.Id).Status__c != 'Approved') {
                assignUserApp.assignUserApp(ar.App__c, HashIds.get(ar.Request_Owner__c).HashId__pc);
            }
        }
    }
}